version: '3.7'
services:
    vue2_front:
        image: vue-frontend:latest
        container_name: vue2-front
        stdin_open: true
        build:
            dockerfile: ./docker/Dockerfile
            context: .
        env_file:
            - ./env/dev.env
        volumes:
            - ./app:/app
        ports:
            - "80:3000"
        environment:
            HOST: 0.0.0.0
            API_URL: "http://laravel-back"
        networks:
            - laravel_core_admin
            
networks:
    laravel_core_admin:
        external: true