version: '3'
services:
    laravel_db:
        container_name: laravel-db
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
        volumes:
            - ./docker/db/mysql.cnf:/etc/mysql/conf.d/custom.cnf
        ports:
            - "3306:3306"
        networks:
            - core_admin
    laravel_http:
        image: nginx:latest
        container_name: laravel-http
        volumes:
            - ./app:/var/www/html
            - ./docker/http/app.conf:/etc/nginx/conf.d/app.conf
        ports:
            - "8080:80"
        networks:
            - core_admin
    laravel_back:
        image: laravel-backend:latest
        build:
            dockerfile: ./docker/php-fpm/Dockerfile
            context: .
        container_name: laravel-back
        env_file:
            - ./env/dev.env
        links:
            - laravel_db:db
        volumes:
            - ./app:/var/www/html
            - ./docker/php-fpm/app.ini:/usr/local/etc/php/conf.d/php-extras.ini
        networks:
            - core_admin

networks:
    core_admin:
        driver: bridge